---
- name: Install and configure Zabbix Agent 2
  hosts: "{{ target_hosts }}"
  become: yes
  vars:
    zabbix_version: 6.4
    zabbix_agent_server: "{{ zabbix_server_IP }}"
    zabbix_agent_serversactive: "{{ zabbix_server_IP }}"
    zabbix_agent_package_state: present
  tasks:
    - name: Install Zabbix repository
      ansible.builtin.yum_repository:
        name: zabbix
        description: Zabbix Official Repository - $basearch
        baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/$basearch/
        gpgcheck: yes
        gpgkey: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        enabled: yes
    - name: Install Zabbix Agent 2
      ansible.builtin.dnf:
        name: zabbix-agent2
        state: "{{ zabbix_agent_package_state }}"
    - name: Configure Zabbix Agent
      ansible.builtin.template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        mode: '0644'
      notify: restart zabbix-agent2
    - name: Ensure Zabbix Agent is running and enabled on boot
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: yes
  handlers:
    - name: restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted